config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  get 'prototypes/newest'  => 'prototypes/newest#index'
  get 'prototypes/popular'  => 'prototypes/popular#index'
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:show, :index]
end

app/models/capturedimage.rb
class Capturedimage < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :prototype

  enum role: [:mainimage, :subimage]
  validates :image, presence: true
  validates :role, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  has_many :capturedimages, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :capturedimages

  acts_as_taggable_on :prototypes
  acts_as_taggable
  acts_as_ordered_taggable_on :prototypes

  paginates_per 8


  validates :name ,presence: true
  validates :catchcopy ,presence: true
  validates :content ,presence:true

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar,AvatarUploader

  validates_confirmation_of :password


  has_many :prototypes
  has_many :likes
  has_many :comments

  paginates_per 8
  


  validates :name, presence: true
  validates :password, length: {minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :works, :member, :profile, :avatar])
  end


end

app/controllers/capturedimages_controller.rb
class CapturedimagesController < ApplicationController
  def new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(params[:prototype_id])
    @prototype.comments.create(comment_params)
  end


  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
    render "likes-box.js.erb"
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
    render "likes-box.js.erb"
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController

  def index
    @prototypes = Prototype.order("created_at DESC").page(params[:page]).per(8)
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.order("likes_count DESC").page(params[:page]).per(8)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

   before_action :set_prototype, only:[:show, :edit, :update, :destroy]
   before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.order("likes_count DESC").page(params[:page])
  end

  def show
    @likes = Like.where(prototype_id: params[:id])
    @comment = Comment.new
  end

  def new
    @prototype = Prototype.new
    @prototype.capturedimages.build
  end

  def create
    @prototype = Prototype.new(create_params)
      if @prototype.save
        flash[:success]="prototype successfully"
        redirect_to :root
      else
        flash[:danger]="prototype unsuccessfully"
        redirect_to new_prototype_path
    end
  end

  def destroy
    if @prototype.user_id == current_user.id
       @prototype.destroy
    end
    flash[:success]="delete complited"
    redirect_to :root
  end

  def edit
    @mainimage = @prototype.capturedimages.first
    @subimage = @prototype.capturedimages.where(role: 1)
  end

  def update
    if @prototype.user_id == current_user.id

      if @prototype.update(update_params)
      flash[:success]="edit complited"
      redirect_to :root
      else
        flash[:danger]="edit failed"
        redirect_to edit_prototype_path
      end
    end
  end



  private

  def create_params
    params.require(:prototype).permit(:name, :catchcopy, :content, :user_id, capturedimages_attributes:[:image, :role]).merge(tag_list: params[:prototype][:tag])
  end

  def update_params
    params.require(:prototype).permit(:name, :catchcopy, :content, :user_id, capturedimages_attributes:[:id, :image, :role]).merge(tag_list: params[:prototype][:tag])
  end

  def set_prototype
    @prototype=Prototype.find(params[:id])
  end



end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:update, :edit ]

  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes.page(params[:page])
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    @user.update(user_params)
    flash[:success]="edit complited"
    redirect_to :root and return
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :member,:profile, :works ,:avatar)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/prototypes_helper.rb
module PrototypesHelper
  def likes_counter(prototype)
    likes.likes_count
  end
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to user_path(comment.user) do
      = image_tag comment.user.avatar, style: "width: 64px; height: 64px;", alt: "64x64"
      / %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      %a.anchorjs-link{href: "#top-aligned-media"}
        %span.anchorjs-icon
    %p
      = comment.comment

app/views/comments/create.js.erb
$('#comment_field').val("");
$('#comment_list').html("<%= j(render partial: 'comments/comment', collection: @prototype.comments) %>");

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              UserName
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                =link_to "My Page", user_path(current_user)
              %li
                =link_to "Profile Edit", edit_user_path(current_user)
              %li
                =link_to "Logout", destroy_user_session_path ,method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_prototype_path
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              =link_to "Get Started",new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    -flash.each do |key, value|
      = content_tag :div, value, class: "alert alert-#{key}"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to prototype_like_path(likes, prototype_id: prototype.id), method: :delete, remote: true do
      = image_tag "icon_heart_red.svg"
      Like
      %span
        = prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype), remote: true do
      = image_tag "icon_heart.svg"
      Like
      %span
        = prototype.likes_count
- else
  = button_to new_user_session_path, :disabled => true do
    = image_tag "icon_heart.svg"
    Like
    %span
      = prototype.likes_count

app/views/likes/likes-box.js.erb
$("#likes-box").html("<%= j(render partial: 'like', locals: { prototype: @prototype, likes: @likes }) %>");

app/views/prototypes/_prototype.html.haml
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        =link_to  prototype do
          =image_tag prototype.capturedimages.first.image
          .caption
            %h3
              =prototype.name
            .proto-meta
              .proto-user
                =link_to "#{prototype.user.name}", user_path(prototype.user_id)
              .proto-posted
                =prototype.created_at.to_s(:updated_at)
            %ul.proto-tag-list.list-inline
              - prototype.tags.each do |tag|
                %li
                  = link_to "#{tag.name}", tag_path(tag.id), class: "btn btn-default"

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype, :url => "/prototypes/#{@prototype.id}", :html => {:method =>:patch} do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.hidden_field :user_id, value: current_user.id
            = f.text_field :name, placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :capturedimages, @mainimage do |mainimage|
              = mainimage.file_field :image
              = mainimage.hidden_field :role, value: "mainimage"
              = image_tag @prototype.capturedimages.first.image, id: "main_preview",style: "width: 100%; height: 100%;"
        .col-md-12
          %ul.proto-sub-list.list-group
            - @subimage.each_with_index do |prototype,i|
              = f.fields_for :capturedimages, prototype do |subimage|
                %li.list-group-item.col-md-4
                  .image-upload
                    = subimage.file_field :image
                    = subimage.hidden_field :role, value: "subimage"
                    = image_tag prototype.image, id: "sub_#{i + 1}_preview",style: "width: 100%; height: 100%;"
      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :content, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag  "prototype[tag][]", "", placeholder: "Web Desighn"
            .col-md-3
              = text_field_tag  "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              = text_field_tag  "prototype[tag][]", "", placeholder: "Application"
      .row.text-center.proto-btn
        .btn.btn-lg.btn-primary.btn-block
          = f.submit "publish"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation", id: "js-active"}
          = link_to "Popular PROTO", prototypes_popular_path, remote: true
        %li{role: "presentation", id: "js-active"}
          = link_to "Newest PROTO", prototypes_newest_path, remote: true
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"
%span#prototype
  = render partial: 'prototypes/prototype', collection: @prototypes
.text-center
  = paginate @prototypes

  / %ul.pagination
  /   %li.disabled

  /     %a{"aria-label" => "Previous", href: "#"}
  /       %span{"aria-hidden" => "true"} «
  /   %li.active
  /     %a{href: "#"}
  /       1
  /       %span.sr-only (current)
  /   %li
  /     %a{href: "#"} 2
  /   %li
  /     %a{href: "#"} 3
  /   %li
  /     %a{href: "#"} 4
  /   %li
  /     %a{href: "#"} 5
  /   %li
  /     %a{"aria-label": "Next", href: "#"}
  /       %span{"aria-hidden": "true"} »

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype, :url => prototypes_path do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.hidden_field :user_id, value: current_user.id
            = f.text_field :name, placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :capturedimages do |mainimage|
              %img#main_preview{style: "width: 100%; height: 100%;"}
              = mainimage.file_field :image
              = mainimage.hidden_field :role, value: "mainimage"
        .col-md-12
          %ul.proto-sub-list.list-group
            - 2.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :capturedimages do |subimage|
                    %img{id: "sub_#{i+1}_preview", style: "width: 100%; height: 100%;"}
                    = subimage.file_field :image
                    = subimage.hidden_field :role, value: "subimage"
            %li.list-group-item.col-md-4.hide_form#plus
              .image-upload
                = f.fields_for :capturedimages do |plusimage|
                  %img#sub_3_preview{style: "width: 100%; height: 100%;"}
                  = plusimage.file_field :image
                  = plusimage.hidden_field :role, value: "subimage"
            %li.list-group-item.col-md-4#add_new_form
              .image-upload-plus
                %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :content, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag  "prototype[tag][]", "", placeholder: "Web Desighn"
              / %input{type: "text", placeholder: "Web Design"}/
            .col-md-3
              = text_field_tag  "prototype[tag][]", "", placeholder: "UI"
              / %input{type: "text", placeholder: "UI"}/
            .col-md-3
              = text_field_tag  "prototype[tag][]", "", placeholder: "Application"
              / %input{type: "text", placeholder: "Application"}/
      .row.text-center.proto-btn
        .btn.btn-lg.btn-primary.btn-block
          = f.submit "publish"

app/views/prototypes/newest/index.js.erb
$("li#js-active").toggleClass("active");
$('#prototype').html("<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>");

app/views/prototypes/popular/index.js.erb
$("li#js-active").toggleClass("active");
$('#prototype').html("<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>");

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to @prototype.user do
            = image_tag @prototype.user.avatar,
                        style: "width: 64px; height: 64px;",
                        alt: "64x64",
                        "data-holder-rendered" => true,
                        "data-src" => "holder.js/64x64",
                        class: "media-object"
        .media-body
          %h4#top-aligned-media.media-heading= @prototype.name
          .proto-user
            = link_to "by #{@prototype.user.name}", @prototype.user
            %span.degree
              = @prototype.user.profile
              = @prototype.user.works

    .col-md-6.text-right
      .btn.btn-defult.increment-button#likes-box
        = render partial: 'likes/like', locals: { prototype: @prototype, likes: @likes }
  .row
    .col-md-9
      =image_tag @prototype.capturedimages.first.image, :class => 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        -@prototype.capturedimages.where(role: 1).each do |capturedimage|
          %li.list-group-item
            = image_tag(capturedimage.image, :class=>'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        =@prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
        =@prototype.content
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          %li
            = link_to "#{tag.name}", tag_path(tag.id), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = @prototype.comments.count
    .col-md-8
      %span#comment_list
        = render partial: 'comments/comment',collection: @prototype.comments
      - if user_signed_in?
        = form_for [@prototype, @comment],  remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :comment , placeholder: "Your comments", rows: "3", class: "form-control", id: "comment_field"
              = f.hidden_field :user_id, value: current_user.id
            .form-group.col-md-2
              = f.submit "Comment", class: "btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    - @tags.each do |tag|
      .col-sm-4.col-sm-3
        = link_to  tag_path(tag.id), class: "tag thumbnail" do
          .tag-name
            = tag.name
          .tag-project
            = tag.taggings_count

app/views/tags/show.html.haml
.container
  .row
    .tag-header
      %span
        = @tag.name
    - @prototypes.each do |prototype|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          = link_to prototype_path(prototype) do
            = image_tag prototype.capturedimages.first.image
          .caption
            %h3
              = prototype.name
            .proto-meta
              .proto-user
                = link_to "#{prototype.user.name}", user_path(prototype.user_id)
              .proto-posted
                = prototype.created_at.to_s(:updated_at)

app/views/users/edit.html.haml
.container.user-new
  =form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              =f.text_field :name, placeholder: "Username"
            .user-image.col-md-2
              = image_tag @user.avatar, style: "width: 75px; height: 75px; border-radius: 100px; position: relative; right: 16px;", alt: "64x64", "data-holder-rendered" => true, "data-src" => "holder.js/64x64", class: "media-object", id: "js-avatar"
              = f.button "Changeimage", class: "btn btn-primary"
              = f.file_field :avatar
          .user-email
            =f.text_field :email, placeholder: "E-mail"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              =f.text_field :member, placeholder: "Member"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              =f.text_area :profile, placeholder:"Profile", cols:"30", rows: "4"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              =f.text_area :works, placeholder: "Works", cols: "30", rows: "4"
      .row.text-center.user-btn
        .btn.btn-lg.btn-primary.btn-block
          =f.submit "Save"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to @user, disabled: true do
          = image_tag @user.avatar,
                      style: "width: 64px; height: 64px;",
                      alt: "64x64",
                      "data-holder-rendered" => true,
                      "data-src" => "holder.js/64x64",
                      class: "media-object"
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Works
            %p
              = @user.works
- @prototypes.each do |prototype|
  .container.proto-list
    .row
      .col-sm-4.col-md-3.proto-content
        .dropdown.drop_menu_location
          %button.btn.btn-defoult.dropdown-toggle{"data-toggle"=>"dropdown","id"=>"dropdownMenu","type"=>"button","aira-expanded"=>"false"}Action
          %ul.dropdown-menu{"aria-labelledy"=>"dropdownMenu1"}
            %li
              = link_to "Delete", prototype_path(prototype),method: :delete
            %li
              = link_to "Edit", edit_prototype_path(prototype)
        .thumbnail
          = link_to prototype_path(prototype) do
            = image_tag prototype.capturedimages.first.image
            .caption
              %h3
                = prototype.name
              .proto-meta
                .proto-date
                  = prototype.created_at.to_formatted_s(:updated_at)

              %ul.proto-tag-list.list-inline
                - prototype.tags.each do |tag|
                  %li
                    = link_to "#{tag.name}",tag_path(tag.id),class: "btn btn-default"
.text-center
  = paginate @prototypes
  / %ul.pagination
  /   %li.disabled
  /     %a{"aria-label": "Previous", href: "#"}
  /       %span{"aria-hidden": "true"} «
  /   %li.active
  /     %a{href: "#"}
  /       1
  /       %span.sr-only (current)
  /   %li
  /     %a{href: "#"} 2
  /   %li
  /     %a{href: "#"} 3
  /   %li
  /     %a{href: "#"} 4
  /   %li
  /     %a{href: "#"} 5
  /   %li
  /     %a{"aria-label": "Next", href: "#"}
  /       %span{"aria-hidden": "true"} »